#!/usr/bin/env perl

# This chunk of stuff was generated by App::FatPacker. To find the original
# file's code, look for the end of this BEGIN block or the string 'FATPACK'
BEGIN {
my %fatpacked;

s/^  //mg for values %fatpacked;

my $class = 'FatPacked::'.(0+\%fatpacked);
no strict 'refs';
*{"${class}::files"} = sub { keys %{$_[0]} };

if ($] < 5.008) {
  *{"${class}::INC"} = sub {
    if (my $fat = $_[0]{$_[1]}) {
      my $pos = 0;
      my $last = length $fat;
      return (sub {
        return 0 if $pos == $last;
        my $next = (1 + index $fat, "\n", $pos) || $last;
        $_ .= substr $fat, $pos, $next - $pos;
        $pos = $next;
        return 1;
      });
    }
  };
}

else {
  *{"${class}::INC"} = sub {
    if (my $fat = $_[0]{$_[1]}) {
      open my $fh, '<', \$fat
        or die "FatPacker error loading $_[1] (could be a perl installation issue?)";
      return $fh;
    }
    return;
  };
}

unshift @INC, bless \%fatpacked, $class;
  } # END OF FATPACK CODE


#====================================================================================================================================================#
#<use>
$|++; #---turn on the auto flush for the progress bar
no warnings 'utf8';
use warnings;
use strict;
use File::Path;
use File::Copy;
use File::Basename;
use File::Spec::Functions qw(rel2abs abs2rel);
use Time::HiRes qw( time );
use Getopt::Long 'HelpMessage';
use threads ('stack_size' => 64*4096);
use threads::shared;
use List::Util qw (sum shuffle min max);
use Cwd 'abs_path';
use AutoLoader qw/AUTOLOAD/;
#<\use>
#====================================================================================================================================================#

#====================================================================================================================================================#
#<doc>
=head1 SYNOPSIS

           5'-O~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~AAA-3'
                        O~~~AA      O~~         O~       O~~~~~~~AO~~~~~~~~A
                      O~~    O~~ O~~   O~~     O~O~~     O~~      O~~       
                       O~~      O~~           O~  O~~    O~~      O~~       
                         O~~    O~~          O~~   O~~   O~~~~~AA O~~~~~~A  
                            O~~ O~~         O~~~~~A O~~  O~~      O~~       
                      O~~    O~~ O~~   O~~ O~~       O~~ O~~      O~~       
                        O~~~~A     O~~~   O~~         O~~O~~      O~~~~~~~AA
       ┌─ᐅ 5'-O~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-3'
 ...===┴========================================================================================...

                      Single Cell Analysis of Five-prime End (SCAFE) Tool Suite 
                                  ---> scafe.tool.cm.aggregate <---
                <--- tool, common mode, aggregate ctss of multiple samples --->

 Description:
   This tool aggregate multiple ctss bed files, regardless of single cell or bulk

 Usage:
   scafe.tool.cm.aggregate [options] --lib_list_path --genome --outputPrefix --outDir
   
   --lib_list_path  <required> [string] a list of libraries, in formation of 
                                        <lib_ID><\t><collapse_ctss><\t><unencoded_G_collapse_ctss>
                                        lib_ID = Unique ID of the lib
                                        collapse_ctss = *.collapse.ctss.bed.gz from scafe.tool.sc.bam_to_ctss or scafe.tool.bk.bam_to_ctss
                                                        or *.pass.ctss.bed.gz from scafe.tool.cm.remove_strand_invader
                                        unencoded_G_collapse_ctss = *unencoded_G.collapse.ctss.bed.gz from 
                                                                    scafe.tool.sc.bam_to_ctss or scafe.tool.bk.bam_to_ctss
   --genome        <required> [string]  name of genome reference, e.g. hg19.gencode_v32lift37
   --outputPrefix  <required> [string]  prefix for the output files
   --outDir        <required> [string]  directory for the output files
   --max_thread    (optional) [integer] maximum number of parallel threads, capped at 10 to 
                                        avoid memory overflow (default=5)
   --overwrite     (optional) [yes/no]  erase outDir/outputPrefix before running (default=no)

 Dependencies:
   bedtools
   tabix
   bgzip
   
 For demo, cd to SCAFE dir and run,
   scafe.tool.cm.aggregate \
   --overwrite=yes \
   --lib_list_path=./demo/input/cm.aggregate/lib_list_path.txt \
   --genome=hg19.gencode_v32lift37 \
   --outputPrefix=demo \
   --outDir=./demo/output/cm.aggregate/aggregate/

=head1 VERSION

v0.9.0-beta [March 20, 2021]
	-Exists as scafe.tool.sc.pool/scafe.tool.bk.pool

v1.0.0 [June 6, 2022]
	-Initial release

v1.0.1 [June 26, 2022]
	-No update

=cut
#<\doc>
#====================================================================================================================================================#

#====================================================================================================================================================#
#<lastCmdCalled>
#
#	notCalledBefore
#
#	notCalledBefore
#
#<\lastCmdCalled>
#====================================================================================================================================================#

#====================================================================================================================================================#
#<global>
my $scriptDirPath = dirname(rel2abs($0));
my $scriptAbsPath = abs_path($0);
my ($curntTimeStamp) = &timeStamp();#->974
my $ARGVStr = join "\n", (&currentTime(), $scriptAbsPath, @ARGV);#->420
my $globalReadmeHsh_ref = {};
our $tmplog_fh;
#<\global>
#====================================================================================================================================================#

#====================================================================================================================================================#
{	#Main sections lexical scope starts
#====================================================================================================================================================#

#====================================================================================================================================================#
#	section 0_startingTasks
#
#<section ID="startingTasks" num="0">
my ($lib_list_path, $max_thread, $genome, $outputPrefix, $outDir, $overwrite) = &readParameters();#->906
#<\section>
#====================================================================================================================================================#

#====================================================================================================================================================#
#	section 1_defineHardCodedParam
#
#<section ID="defineHardCodedParam" num="1">
my $paramTag = "$outputPrefix";
my $num_chunk = 100;
my $bgzip_sort_thread = 5;
$max_thread = 10 if $max_thread > 10;
my $rm_tmp_file = 'yes';
#<\section>
#====================================================================================================================================================#

#====================================================================================================================================================#
#	section 2_defineOutDirPath
#
#<section ID="defineOutDirPath" num="2">
my @mkDirAry;
my $result_dir = "$outDir/$paramTag"; push @mkDirAry, $result_dir;
system "rm -rf $result_dir" if ($overwrite eq 'yes');
my $result_bed_dir = "$result_dir/bed/"; push @mkDirAry, $result_bed_dir;
my $result_log_dir = "$result_dir/log/"; push @mkDirAry, $result_log_dir;
my $result_tmp_dir = "$result_dir/tmp/"; push @mkDirAry, $result_tmp_dir;
my $result_script_dir = "$result_dir/script/"; push @mkDirAry, $result_script_dir;
foreach my $dir (@mkDirAry) {system ("mkdir -pm 755 $dir");}
open $tmplog_fh, ">", "$result_dir/00_screen_log.$curntTimeStamp.log.txt";
&logCalledCMDAndScript($ARGVStr, $result_script_dir, $scriptAbsPath);#->536
&printStartOrFinishMessage("startMessage");#->767
my ($tabix_bin, $bgzip_bin, $bedtools_bin, $samtools_bin, $paraclu_bin, $cut_sh_path, $bedGraphToBigWig_bin, $bigWigAverageOverBed_bin) = &checkAllExecutable();#->203
#<\section>
#====================================================================================================================================================#

#====================================================================================================================================================#
#	section 3_generate_chunk
#
#<section ID="generate_chunk" num="3">
my ($chrom_size_path) = &checkChromSizePath($genome);#->303
my ($chrom_size_hsh_ref) = &generateChromSizeHsh($chrom_size_path);#->438
my ($chunk_size) = &generateChunkSize($chrom_size_hsh_ref, $num_chunk);#->511
my ($chunk_info_hsh_ref) = &generateChunkInfoHsh($chrom_size_hsh_ref, $chunk_size, $result_tmp_dir);#->464
my ($lib_info_hsh_ref) = &readLibInfo($lib_list_path);#->881
($lib_info_hsh_ref) = &checkTabixBgzipCtss($tabix_bin, $bgzip_bin, $lib_info_hsh_ref, $max_thread, $result_tmp_dir, $bgzip_sort_thread);#->346
#<\section>
#====================================================================================================================================================#

#====================================================================================================================================================#
#	section 4_convert
#
#<section ID="convert" num="4">
&processPerChunk($lib_info_hsh_ref, $bedtools_bin, $max_thread, $chunk_info_hsh_ref, $bgzip_sort_thread, $tabix_bin, $bgzip_bin);#->801
&poolChunkResults($chunk_info_hsh_ref, $result_bed_dir, $result_log_dir, $paramTag, $result_tmp_dir, $rm_tmp_file, $tabix_bin);#->561
#<\section>
#====================================================================================================================================================#

#====================================================================================================================================================#
#	section 5_finishingTasks
#
#<section ID="finishingTasks" num="5">
&printOutputFileListAndReadme($ARGVStr, $paramTag, $outDir);#->652
&printStartOrFinishMessage("finishMessage");#->767
#<\section>
#====================================================================================================================================================#

#====================================================================================================================================================#
}	#Main sections lexical scope ends
#====================================================================================================================================================#

#====================================================================================================================================================#
#List of subroutines by category
#
#	general [n=5]:
#		currentTime, logCalledCMDAndScript, printStartOrFinishMessage
#		readParameters, timeStamp
#
#	log [n=1]:
#		reportAndLogStatus
#
#	output [n=1]:
#		printOutputFileListAndReadme
#
#	time [n=1]:
#		timeStamp
#
#	unassigned [n=11]:
#		checkAllExecutable, checkChromSizePath, checkChunkResults
#		checkTabixBgzipCtss, generateChromSizeHsh, generateChunkInfoHsh
#		generateChunkSize, poolChunkResults, poolLibCTSSPerChunk
#		processPerChunk, readLibInfo
#
#====================================================================================================================================================#

sub checkAllExecutable {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: reportAndLogStatus|952
#	appearInSub: >none
#	primaryAppearInSection: 2_defineOutDirPath|125
#	secondaryAppearInSection: >none
#	input: none
#	output: $bedGraphToBigWig_bin, $bedtools_bin, $bgzip_bin, $bigWigAverageOverBed_bin, $cut_sh_path, $paraclu_bin, $samtools_bin, $tabix_bin
#	toCall: my ($tabix_bin, $bgzip_bin, $bedtools_bin, $samtools_bin, $paraclu_bin, $cut_sh_path, $bedGraphToBigWig_bin, $bigWigAverageOverBed_bin) = &checkAllExecutable();
#	calledInLine: 139
#....................................................................................................................................................#
	
	my $dirPath = dirname(rel2abs($0));

	my $tabix_bin = "$dirPath/../resources/bin/tabix/tabix";
	my $bgzip_bin = "$dirPath/../resources/bin/bgzip/bgzip";
	my $bedtools_bin = "$dirPath/../resources/bin/bedtools/bedtools";
	my $samtools_bin = "$dirPath/../resources/bin/samtools/samtools";
	my $paraclu_bin = "$dirPath/../resources/bin/paraclu/paraclu";
	my $cut_sh_path = "$dirPath/../resources/bin/paraclu/paraclu-cut.sh";
	my $bedGraphToBigWig_bin = "$dirPath/../resources/bin/bedGraphToBigWig/bedGraphToBigWig";
	my $bigWigAverageOverBed_bin = "$dirPath/../resources/bin/bigWigAverageOverBed/bigWigAverageOverBed";
	
	&reportAndLogStatus("Checking all SCAFE executables", 10, "\n");#->952
	
	{
		my $stdOut = `$tabix_bin  --version 2>&1`;
		if ($stdOut =~ m/tabix \(htslib\) (\S+)/) {
			&reportAndLogStatus("Checking: tabix version: $1", 0, "\n");#->952
		} else {
			die "tabix is not installed properly. Quitting.\n";
		}
	}

	{
		my $stdOut = `$bgzip_bin --version 2>&1`;
		if ($stdOut =~ m/bgzip \(htslib\) (\S+)/) {
			&reportAndLogStatus("Checking: bgzip version: $1", 0, "\n");#->952
		} else {
			die "bgzip is not installed properly. Quitting.\n";
		}
	}

	{
		my $stdOut = `$bedtools_bin --version 2>&1`;
		if ($stdOut =~ m/bedtools v(\S+)/) {
			&reportAndLogStatus("Checking: bedtools version: $1", 0, "\n");#->952
		} else {
			die "bedtools is not installed properly. Quitting.\n";
		}
	}

	{
		my $stdOut = `$samtools_bin 2>&1`;
		if ($stdOut =~ m/\s+(Version: \S+)\s+/) {
			&reportAndLogStatus("Checking: samtools version: $1", 0, "\n");#->952
		} else {
			die "samtools is not installed properly. Quitting.\n";
		}
	}
	
	{
		my $stdOut = `$paraclu_bin 2>&1`;
		if ($stdOut =~ m/paraclu: I need a minValue and a fileName/) {
			&reportAndLogStatus("Checking: paraclu found.", 0, "\n");#->952
		} else {
			die "paraclu is not installed properly. Quitting.\n";
		}
	}
	
	{
		my $stdOut = `$cut_sh_path 55C7128A 2>&1`;
		if ($stdOut =~ m/awk:/) {
			&reportAndLogStatus("Checking: paraclu-cut found.", 0, "\n");#->952
		} else {
			die "paraclu-cut is not installed properly. Quitting.\n";
		}
	}

	{
		my $stdOut = `$bedGraphToBigWig_bin 2>&1`;
		if ($stdOut =~ m/bedGraphToBigWig v (\S+)/) {
			&reportAndLogStatus("Checking: bedGraphToBigWig version: $1", 0, "\n");#->952
		} else {
			die "bedGraphToBigWig not installed properly. Quitting.\n";
		}
	}

	{
		my $stdOut = `$bigWigAverageOverBed_bin 2>&1`;
		if ($stdOut =~ m/bigWigAverageOverBed v(\S+)/) {
			&reportAndLogStatus("Checking: bigWigAverageOverBed version: $1", 0, "\n");#->952
		} else {
			die "bigWigAverageOverBed is not installed properly. Quitting.\n";
		}
	}

	return ($tabix_bin, $bgzip_bin, $bedtools_bin, $samtools_bin, $paraclu_bin, $cut_sh_path, $bedGraphToBigWig_bin, $bigWigAverageOverBed_bin);
}
sub checkChromSizePath {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 3_generate_chunk|144
#	secondaryAppearInSection: >none
#	input: $genome
#	output: $chrom_size_path
#	toCall: my ($chrom_size_path) = &checkChromSizePath($genome);
#	calledInLine: 147
#....................................................................................................................................................#
	my ($genome) = @_;
	
	my $dirPath = dirname(rel2abs($0));
	my $chrom_size_path = "$dirPath/../resources/genome/$genome/tsv/chrom.sizes.tsv";
	die "genome $genome does not have chrom_size_path. Please rerun prep_genome step\n" if not -s $chrom_size_path;
	
	return ($chrom_size_path);
}
sub checkChunkResults {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: reportAndLogStatus|952
#	appearInSub: poolChunkResults|561, processPerChunk|801
#	primaryAppearInSection: >none
#	secondaryAppearInSection: 4_convert|157
#	input: $chunk_info_hsh_ref, $chunk_num, $file_check_ary_ref
#	output: $valid
#	toCall: my ($valid) = &checkChunkResults($chunk_info_hsh_ref, $chunk_num, $file_check_ary_ref);
#	calledInLine: 584, 839
#....................................................................................................................................................#
	my ($chunk_info_hsh_ref, $chunk_num, $file_check_ary_ref) = @_;
	
	my $valid = 'yes';
	foreach my $file_to_check (@{$file_check_ary_ref}) {
		my $file_path =  $chunk_info_hsh_ref->{$chunk_num}{'ctss'}{'sorted'}{$file_to_check};
		#&reportAndLogStatus("$file_path", 10, "\n");#->952
		$valid = 'no' if not -f $file_path;
	}
	
	return ($valid);
}
sub checkTabixBgzipCtss {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: reportAndLogStatus|952
#	appearInSub: >none
#	primaryAppearInSection: 3_generate_chunk|144
#	secondaryAppearInSection: >none
#	input: $bgzip_bin, $bgzip_sort_thread, $lib_info_hsh_ref, $max_thread, $result_tmp_dir, $tabix_bin
#	output: $lib_info_hsh_ref
#	toCall: my ($lib_info_hsh_ref) = &checkTabixBgzipCtss($tabix_bin, $bgzip_bin, $lib_info_hsh_ref, $max_thread, $result_tmp_dir, $bgzip_sort_thread);
#	calledInLine: 152
#....................................................................................................................................................#
	my ($tabix_bin, $bgzip_bin, $lib_info_hsh_ref, $max_thread, $result_tmp_dir, $bgzip_sort_thread) = @_;
	
	my %itemForThrHsh = ();
	my $threadID = 1;
	foreach my $libID (shuffle(keys %{$lib_info_hsh_ref})) {
		$threadID = 1 if $threadID > $max_thread;
		push @{$itemForThrHsh{$threadID}} , $libID;
		$threadID++;
	}
	
	my %threadHsh =();
	foreach my $threadID (sort keys %itemForThrHsh) {
		my $itemForThrAry_ref = $itemForThrHsh{$threadID};
		($threadHsh{$threadID}) = threads->new(#---refer to http://www.perlmonks.org/?node_id=966781, the 
	
			sub {
				my ($itemForThrAry_ref) = @_;
				my $lib_info_inThr_hsh_ref = {};
				foreach my $libID (@{$itemForThrAry_ref}) {
					#---[2/19/16 13:13] do something on the item here
					foreach my $ctss_type (qw/unencoded_G_collapse_ctss collapse_ctss/) {
						my $original_ctss_path = $lib_info_hsh_ref->{$libID}{$ctss_type};
						my $check_original_index = `$tabix_bin -l $original_ctss_path 2>&1`;
						#&reportAndLogStatus("$check_original_index", 10, "\n");#->952
						my $tabix_ctss_path = $original_ctss_path;
						if ($check_original_index =~ m/Could not load .tbi index/) {
							$tabix_ctss_path = "$result_tmp_dir/$libID.$ctss_type.bed.gz";
							&reportAndLogStatus("Creating tabix index of $ctss_type in $libID", 10, "\n");#->952
							system "$bgzip_bin -@ $bgzip_sort_thread -dc $original_ctss_path | $bgzip_bin -@ $bgzip_sort_thread -c >$tabix_ctss_path";
							system "$tabix_bin -p bed $tabix_ctss_path";
						} else {
							&reportAndLogStatus("Tabix index found for $ctss_type in $libID", 10, "\n");#->952
						}
						my $check_tabix_index = `$tabix_bin -l $tabix_ctss_path 2>&1`;
						die "Tabix index failed for for $ctss_type in $libID" if ($check_tabix_index =~ m/Could not load .tbi index/);
						$lib_info_inThr_hsh_ref->{$libID}{'tabix_ctss_path'}{$ctss_type} = $tabix_ctss_path;
					}
				}
				return ($lib_info_inThr_hsh_ref);
			}
			,($itemForThrAry_ref)
		);
	}
	
	my $data_hsh_ref = {};
	while (keys %threadHsh) {
		foreach my $threadID (keys %threadHsh) {
			if (not $threadHsh{$threadID}->is_running()) {
				my ($lib_info_inThr_hsh_ref) = $threadHsh{$threadID}->join;
				foreach my $libID (keys %{$lib_info_inThr_hsh_ref}) {
					foreach my $ctss_type (keys %{$lib_info_inThr_hsh_ref->{$libID}{'tabix_ctss_path'}}) {
						$lib_info_hsh_ref->{$libID}{'tabix_ctss_path'}{$ctss_type} = $lib_info_inThr_hsh_ref->{$libID}{'tabix_ctss_path'}{$ctss_type};
					}
				}
				delete $threadHsh{$threadID};
			}
		}
		sleep 1;
	}
	
	return ($lib_info_hsh_ref);
}
sub currentTime {
#....................................................................................................................................................#
#	subroutineCategory: general
#	dependOnSub: >none
#	appearInSub: printStartOrFinishMessage|767, reportAndLogStatus|952
#	primaryAppearInSection: >none
#	secondaryAppearInSection: 2_defineOutDirPath|125, 5_finishingTasks|166
#	input: none
#	output: $runTime
#	toCall: my ($runTime) = &currentTime();
#	calledInLine: 94, 783, 787, 792, 796, 968, 969
#....................................................................................................................................................#
	
	my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime(time);
	my $runTime = sprintf "%04d-%02d-%02d %02d:%02d", $year+1900, $mon+1,$mday,$hour,$min;	
	
	return $runTime;
}
sub generateChromSizeHsh {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 3_generate_chunk|144
#	secondaryAppearInSection: >none
#	input: $chrom_size_path
#	output: $chrom_size_hsh_ref
#	toCall: my ($chrom_size_hsh_ref) = &generateChromSizeHsh($chrom_size_path);
#	calledInLine: 148
#....................................................................................................................................................#
	
	my ($chrom_size_path) = @_;
	
	my $chrom_size_hsh_ref = {};
	open (CHROMSIZE, "<", $chrom_size_path);
	while (<CHROMSIZE>) {
		chomp;
		my ($chrom, $size) = split /\s+/;
		$chrom_size_hsh_ref->{$chrom} = $size;
	}
	close CHROMSIZE;

	return ($chrom_size_hsh_ref);
}
sub generateChunkInfoHsh {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: reportAndLogStatus|952
#	appearInSub: >none
#	primaryAppearInSection: 3_generate_chunk|144
#	secondaryAppearInSection: >none
#	input: $chrom_size_hsh_ref, $chunk_size, $result_tmp_dir
#	output: $chunk_info_hsh_ref
#	toCall: my ($chunk_info_hsh_ref) = &generateChunkInfoHsh($chrom_size_hsh_ref, $chunk_size, $result_tmp_dir);
#	calledInLine: 150
#....................................................................................................................................................#
	my ($chrom_size_hsh_ref, $chunk_size, $result_tmp_dir) = @_;
	
	my $chunk_num = 1;
	my $chunk_info_hsh_ref = {};
	foreach my $chrom (sort {$a cmp $b} keys %{$chrom_size_hsh_ref}) {
		my $size = $chrom_size_hsh_ref->{$chrom};
		foreach (my $startPos = 0; $startPos <= $size; $startPos += $chunk_size) {
			my $endPos = $startPos + $chunk_size ;
			$endPos = $size if ($endPos > $size);
			my $file_tag = "$chrom.$startPos.$endPos";
			
			my $size_in_chunk = $endPos - $startPos;
			&reportAndLogStatus("chunk $chunk_num contains $size_in_chunk nt covering $chrom $startPos to $endPos", 10, "\n");#->952
			
			my $chunk_sorted_unencoded_G_collapse_ctss = "$result_tmp_dir/$file_tag.sorted.merged.unencoded_G_collapsed.ctss.bed.gz";
			my $chunk_sorted_collapse_ctss = "$result_tmp_dir/$file_tag.sorted.merged.strand_invader_removed.ctss.bed.gz";
			my $chunk_unsort_unencoded_G_collapse_ctss = "$result_tmp_dir/$file_tag.unsorted.unencoded_G_collapsed.ctss.bed";
			my $chunk_unsort_collapse_ctss = "$result_tmp_dir/$file_tag.unsorted.strand_invader_removed.ctss.bed";

			my ($chunk_chrom, $chunk_startPos, $chunk_endPos) = ($chrom, $startPos, $endPos);
			my $tabix_startPos = $chunk_startPos + 1; #---[2021/09/01 22:58] everything is zero based except tabix
			$chunk_info_hsh_ref->{$chunk_num}{'file_tag'} = $file_tag;
			$chunk_info_hsh_ref->{$chunk_num}{'loc'} = [$chunk_chrom, $chunk_startPos, $chunk_endPos];
			$chunk_info_hsh_ref->{$chunk_num}{'region_str'} = "$chunk_chrom:$chunk_startPos-$chunk_endPos";
			$chunk_info_hsh_ref->{$chunk_num}{'tabix_region_str'} = "$chunk_chrom:$tabix_startPos-$chunk_endPos";
			$chunk_info_hsh_ref->{$chunk_num}{'ctss'}{'unsort'}{'collapse_ctss'} = $chunk_unsort_collapse_ctss;
			$chunk_info_hsh_ref->{$chunk_num}{'ctss'}{'unsort'}{'unencoded_G_collapse_ctss'} = $chunk_unsort_unencoded_G_collapse_ctss;
			$chunk_info_hsh_ref->{$chunk_num}{'ctss'}{'sorted'}{'collapse_ctss'} = $chunk_sorted_collapse_ctss;
			$chunk_info_hsh_ref->{$chunk_num}{'ctss'}{'sorted'}{'unencoded_G_collapse_ctss'} = $chunk_sorted_unencoded_G_collapse_ctss;
			$chunk_num++;
		}
 	}

	return ($chunk_info_hsh_ref);
}
sub generateChunkSize {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 3_generate_chunk|144
#	secondaryAppearInSection: >none
#	input: $chrom_size_hsh_ref, $num_chunk
#	output: $chunk_size
#	toCall: my ($chunk_size) = &generateChunkSize($chrom_size_hsh_ref, $num_chunk);
#	calledInLine: 149
#....................................................................................................................................................#
	
	my ($chrom_size_hsh_ref, $num_chunk) = @_;
	
	my $total_size = 0;

	foreach my $chrom (keys %{$chrom_size_hsh_ref}) {
		$total_size += $chrom_size_hsh_ref->{$chrom};
	}
	
	my $chunk_size = int ($total_size/$num_chunk);

	return ($chunk_size);
}
sub logCalledCMDAndScript {
#....................................................................................................................................................#
#	subroutineCategory: general
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 2_defineOutDirPath|125
#	secondaryAppearInSection: >none
#	input: $ARGVStr, $result_script_dir, $scriptAbsPath
#	output: 
#	toCall: &logCalledCMDAndScript($ARGVStr, $result_script_dir, $scriptAbsPath);
#	calledInLine: 137
#....................................................................................................................................................#
	my ($ARGVStr, $result_script_dir, $scriptAbsPath) = @_;


	my $cpScriptPath = "$result_script_dir/script.ran.pl";
	my $calledCMDPath = "$result_script_dir/called.cmd.txt";
	system "cp -f $scriptAbsPath $cpScriptPath";
	system "chmod 0444 $cpScriptPath"; #---[07/03/2014 18:02] make it read-only to make sure there'll be accodental change of parameters
	open CALLEDCMD, ">", $calledCMDPath;
	print CALLEDCMD join "", ($ARGVStr), "\n";
	close CALLEDCMD;
	
	return ();
}
sub poolChunkResults {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: checkChunkResults|323, reportAndLogStatus|952
#	appearInSub: >none
#	primaryAppearInSection: 4_convert|157
#	secondaryAppearInSection: >none
#	input: $chunk_info_hsh_ref, $paramTag, $result_bed_dir, $result_log_dir, $result_tmp_dir, $rm_tmp_file, $tabix_bin
#	output: 
#	toCall: &poolChunkResults($chunk_info_hsh_ref, $result_bed_dir, $result_log_dir, $paramTag, $result_tmp_dir, $rm_tmp_file, $tabix_bin);
#	calledInLine: 161
#....................................................................................................................................................#
	my ($chunk_info_hsh_ref, $result_bed_dir, $result_log_dir, $paramTag, $result_tmp_dir, $rm_tmp_file, $tabix_bin) = @_;
	
	my $out_bed_hsh_ref = {
		'collapse_ctss' => "$result_bed_dir/$paramTag.aggregate.collapse.ctss.bed.gz",
		'unencoded_G_collapse_ctss' => "$result_bed_dir/$paramTag.aggregate.unencoded_G.collapse.ctss.bed.gz",
	};
	
	foreach my $ctss_type (keys %{$out_bed_hsh_ref}) {
		my $out_ctss_type = $out_bed_hsh_ref->{$ctss_type};
		my @file_path_ary = ();
		foreach my $chunk_num (sort {$a <=> $b} keys %{$chunk_info_hsh_ref}) {
			my $file_check_ary_ref = [$ctss_type];
			my ($valid) = &checkChunkResults($chunk_info_hsh_ref, $chunk_num, $file_check_ary_ref);#->323
			if ($valid eq 'yes') {
				my $chunk_sorted_ctss = $chunk_info_hsh_ref->{$chunk_num}{'ctss'}{'sorted'}{$ctss_type};
				push @file_path_ary, $chunk_sorted_ctss;
				&reportAndLogStatus("$ctss_type of chunk $chunk_num is found", 10, "\n");#->952
			} else {
				die "results of chunk $chunk_num is not found. quitting\n";
			}
		}
		&reportAndLogStatus("Concatenating $ctss_type files", 10, "\n");#->952
		my $file_path_str = join " ", @file_path_ary;
		system "cat $file_path_str >$out_ctss_type";
		&reportAndLogStatus("Tabix indexing combined $ctss_type", 10, "\n");#->952
		system "$tabix_bin -p bed $out_ctss_type";
	}
	
	if ($rm_tmp_file eq 'yes') {
		&reportAndLogStatus("Removing result_tmp_dir", 10, "\n");#->952
		system "rm -rf $result_tmp_dir";
	}

	return ();
}
sub poolLibCTSSPerChunk {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: reportAndLogStatus|952
#	appearInSub: processPerChunk|801
#	primaryAppearInSection: >none
#	secondaryAppearInSection: 4_convert|157
#	input: $bedtools_bin, $bgzip_bin, $bgzip_sort_thread, $chunk_info_hsh_ref, $chunk_num, $lib_info_hsh_ref, $tabix_bin
#	output: 
#	toCall: &poolLibCTSSPerChunk($lib_info_hsh_ref, $chunk_info_hsh_ref, $chunk_num, $bgzip_sort_thread, $tabix_bin, $bedtools_bin, $bgzip_bin);
#	calledInLine: 846
#....................................................................................................................................................#
	my ($lib_info_hsh_ref, $chunk_info_hsh_ref, $chunk_num, $bgzip_sort_thread, $tabix_bin, $bedtools_bin, $bgzip_bin) = @_;

	my $tabix_region_str = $chunk_info_hsh_ref->{$chunk_num}{'tabix_region_str'};
	#---[2021/08/22 14:45] tabix_region_str has a 1 based start position to prevent overlapping of the chunk junction
	foreach my $ctss_type (qw/collapse_ctss unencoded_G_collapse_ctss/) {
		my $chunk_unsort_ctss = $chunk_info_hsh_ref->{$chunk_num}{'ctss'}{'unsort'}{$ctss_type};
		my $chunk_sorted_ctss = $chunk_info_hsh_ref->{$chunk_num}{'ctss'}{'sorted'}{$ctss_type};
		my $num_read = 0;
		open UNSORT, ">$chunk_unsort_ctss";
		foreach my $libID (keys %{$lib_info_hsh_ref}) {
			&reportAndLogStatus("pooling $libID in chunk $chunk_num $ctss_type", 10, "\n");#->952
			my $tabix_ctss_path = $lib_info_hsh_ref->{$libID}{'tabix_ctss_path'}{$ctss_type};
			open (TABIX, "$tabix_bin $tabix_ctss_path $tabix_region_str |");
			while (<TABIX>) {
				print UNSORT $_;
				$num_read++;
			}
			close TABIX;
		}
		close UNSORT;
		
		&reportAndLogStatus("sorting and merging $ctss_type in chunk $chunk_num.", 10, "\n");#->952
		if ($num_read > 0) {
			system "sort --parallel $bgzip_sort_thread -k2,2n -k6,6 $chunk_unsort_ctss | $bedtools_bin merge -d -1 -s -c 4,5,6 -o sum,sum,distinct | $bgzip_bin -@ $bgzip_sort_thread >$chunk_sorted_ctss";
		} else {
			system "$bgzip_bin < /dev/null >$chunk_sorted_ctss";
		}
		system "rm $chunk_unsort_ctss";
	}

	return ();
}
sub printOutputFileListAndReadme {
#....................................................................................................................................................#
#	subroutineCategory: output
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 5_finishingTasks|166
#	secondaryAppearInSection: >none
#	input: $ARGVStr, $outDir, $paramTag
#	output: 
#	toCall: &printOutputFileListAndReadme($ARGVStr, $paramTag, $outDir);
#	calledInLine: 169
#....................................................................................................................................................#
	my ($ARGVStr, $paramTag, $outDir) = @_;
	
	my $outputFileListPath = "$outDir/$paramTag/output.file.list.txt";
	open (OUTFILELIST, ">", $outputFileListPath);

	my %dirHsh = ();
	my %filelistLenCountHsh = ();
	push @{$filelistLenCountHsh{'dir'}}, length 'Directory';
	push @{$filelistLenCountHsh{'name'}}, length 'Name';
	push @{$filelistLenCountHsh{'description'}}, length 'Description';
	
	foreach my $outputFilePath (sort {$a cmp $b} keys %{$globalReadmeHsh_ref}) {
		my $fileDescription =  $globalReadmeHsh_ref->{$outputFilePath}{'description'};
		my $cleandOutputFilePath = $outputFilePath;
		$cleandOutputFilePath =~ s/\/+/\//g;
		
		my ($filePrefix, $fileDir, $fileSuffix) = fileparse($cleandOutputFilePath, qr/\.[^.]*/);
		$fileDir =~ s/^$outDir//;
		my $fileName = $filePrefix.$fileSuffix;
		$dirHsh{$fileDir}{$fileName} = $fileDescription;
		push @{$filelistLenCountHsh{'dir'}}, length $fileDir;
		push @{$filelistLenCountHsh{'name'}}, length $fileName;
		push @{$filelistLenCountHsh{'description'}}, length $fileDescription;
		
		open README, ">", "$outputFilePath.readme.txt";
		print README "=================\n";
		print README "File descriptions\n";
		print README "=================\n";
		print README "$fileDescription\n";
					
		if (exists $globalReadmeHsh_ref->{$outputFilePath}{'headerAry'}) {
			my @colLenCountHsh = (length 'column');
			push @colLenCountHsh, length $_ foreach (@{$globalReadmeHsh_ref->{$outputFilePath}{'headerAry'}});
			my $headerColLen = max(@colLenCountHsh)+2;
			print README "\n";
			print README "\n";
			print README "===================\n";
			print README "Column descriptions\n";
			print README "===================\n";
			print README "\n";
			printf README "%-".$headerColLen."s", 'column';
			print README "description\n";
			printf README "%-".$headerColLen."s", '------';
			print README "-----------\n";
			foreach my $header (@{$globalReadmeHsh_ref->{$outputFilePath}{'headerAry'}}) {
				my $columnDescription = 'self-explanatory';
				$columnDescription = $globalReadmeHsh_ref->{$outputFilePath}{'header'}{$header} if exists $globalReadmeHsh_ref->{$outputFilePath}{'header'}{$header};
				printf README "%-".$headerColLen."s", $header;
				print README $columnDescription."\n";
			}
		}
		
		if (exists $globalReadmeHsh_ref->{$outputFilePath}{'extra_info'}) {
			print README "\n";
			print README "\n";
			print README "=================\n";
			print README "Extra information\n";
			print README "=================\n";
			print README "\n";
			foreach my $title (sort keys %{$globalReadmeHsh_ref->{$outputFilePath}{'extra_info'}}) {
				print README "$title\n";
				print README "-" foreach (1..length $title);
				print README "\n";
				print README "$_\n" foreach @{$globalReadmeHsh_ref->{$outputFilePath}{'extra_info'}{$title}};
			}
		}
		
		print README "\n";
		print README "\n";
		print README "~" foreach (1..length "$fileName was created from running,");
		print README "\n";
		print README "$fileName was created from running,\n";
		print README "\n";
		print README "$ARGVStr\n";
		print README "\n";
		close README;
	}

	my $fileDir_colLen = max(@{$filelistLenCountHsh{'dir'}})+2;
	my $fileName_colLen = max(@{$filelistLenCountHsh{'name'}})+2;
	my $fileDescription_colLen = max(@{$filelistLenCountHsh{'description'}})+2;
	printf OUTFILELIST ("%-".$fileDir_colLen."s %-".$fileName_colLen."s %-".$fileDescription_colLen."s\n", 'directory', 'name', 'description');
	printf OUTFILELIST ("%-".$fileDir_colLen."s %-".$fileName_colLen."s %-".$fileDescription_colLen."s\n", '=========', '====', '===========');
	foreach my $fileDir (sort {$a cmp $b} keys %dirHsh) {
		foreach my $fileName (sort {$a cmp $b} keys %{$dirHsh{$fileDir}}) {
			my $fileDescription = $dirHsh{$fileDir}{$fileName};	
			printf OUTFILELIST ("%-".$fileDir_colLen."s %-".$fileName_colLen."s %-".$fileDescription_colLen."s\n", $fileDir, $fileName, $fileDescription);
		}
	}
	
	print OUTFILELIST "\n";
	print OUTFILELIST "\n";
	print OUTFILELIST "~" foreach (1..length "The above files were generated by running,");
	print OUTFILELIST "\n";
	print OUTFILELIST "The above files were generated by running,\n";
	print OUTFILELIST "\n";
	print OUTFILELIST "$ARGVStr\n";
	print OUTFILELIST "\n";

	close OUTFILELIST;

	return ();
}
sub printStartOrFinishMessage {
#....................................................................................................................................................#
#	subroutineCategory: general
#	dependOnSub: currentTime|420
#	appearInSub: >none
#	primaryAppearInSection: 2_defineOutDirPath|125, 5_finishingTasks|166
#	secondaryAppearInSection: >none
#	input: $StartOrFinishMessage
#	output: none
#	toCall: &printStartOrFinishMessage($StartOrFinishMessage);
#	calledInLine: 138, 170
#....................................................................................................................................................#

	my ($StartOrFinishMessage) = @_;
	
	if ($StartOrFinishMessage eq "startMessage") {
		print "\n=========================================================================\n";
		print "[".&currentTime()."] starts running ...... \n";#->420
		print "=========================================================================\n\n";

		print $tmplog_fh "\n=========================================================================\n";
		print $tmplog_fh "[".&currentTime()."] starts running ...... \n";#->420
		print $tmplog_fh "=========================================================================\n\n";

	} elsif ($StartOrFinishMessage eq "finishMessage") {
		print "\n=========================================================================\n";
		print "[".&currentTime()."] finished running .......\n";#->420
		print "=========================================================================\n\n";

		print $tmplog_fh "\n=========================================================================\n";
		print $tmplog_fh "[".&currentTime()."] finished running .......\n";#->420
		print $tmplog_fh "=========================================================================\n\n";
	}
}
sub processPerChunk {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: checkChunkResults|323, poolLibCTSSPerChunk|608, reportAndLogStatus|952
#	appearInSub: >none
#	primaryAppearInSection: 4_convert|157
#	secondaryAppearInSection: >none
#	input: $bedtools_bin, $bgzip_bin, $bgzip_sort_thread, $chunk_info_hsh_ref, $lib_info_hsh_ref, $max_thread, $tabix_bin
#	output: 
#	toCall: &processPerChunk($lib_info_hsh_ref, $bedtools_bin, $max_thread, $chunk_info_hsh_ref, $bgzip_sort_thread, $tabix_bin, $bgzip_bin);
#	calledInLine: 160
#....................................................................................................................................................#
	my ($lib_info_hsh_ref, $bedtools_bin, $max_thread, $chunk_info_hsh_ref, $bgzip_sort_thread, $tabix_bin, $bgzip_bin) = @_;

	my %itemForThrHsh = ();
	my $threadID = 1;
	my $chrom_info_hsh_ref = {};
	my $total_num_chunk = keys %{$chunk_info_hsh_ref};
	foreach my $chunk_num (keys %{$chunk_info_hsh_ref}) {
		$threadID = 1 if $threadID > $max_thread;
		$itemForThrHsh{$threadID}{$chunk_num}++;
		$threadID++;
	}
	my $num_proc : shared = 0;

	my %threadHsh =();
	foreach my $threadID (sort {$a <=> $b} keys %itemForThrHsh) {
		my $itemForThrHsh_ref = $itemForThrHsh{$threadID};
		($threadHsh{$threadID}) = threads->new(#---refer to http://www.perlmonks.org/?node_id=966781, the 
	
			sub {
				
				my ($itemForThrHsh_ref) = @_;
				my $total_chunk = keys %{$itemForThrHsh_ref};
				
				&reportAndLogStatus("$total_chunk chunks spawned to thread $threadID.", 10, "\n");#->952
				foreach my $chunk_num (keys %{$itemForThrHsh_ref}) {
					
					my $file_check_ary_ref = [qw/unencoded_G_collapse_ctss collapse_ctss/];
					my ($valid) = &checkChunkResults($chunk_info_hsh_ref, $chunk_num, $file_check_ary_ref);#->323

					if ($valid eq 'yes') {
						&reportAndLogStatus("results of chunk $chunk_num is found. skipping", 10, "\n");#->952

					} else {
						&reportAndLogStatus("start processing chunk $chunk_num in thread $threadID.", 10, "\n");#->952
						&poolLibCTSSPerChunk($lib_info_hsh_ref, $chunk_info_hsh_ref, $chunk_num, $bgzip_sort_thread, $tabix_bin, $bedtools_bin, $bgzip_bin);#->608
					}
					$num_proc++;
					&reportAndLogStatus("$num_proc of $total_num_chunk chunks are finised.", 10, "\n");#->952
				}
				return ();
			}
			,($itemForThrHsh_ref)
		);
	}
	
	while (keys %threadHsh) {

		my @threads = threads->list();
		my $thread_count = threads->list();
		my @running = threads->list(threads::running);
		my @joinable = threads->list(threads::joinable);
		my $running_count = @running;
		my $joinable_count = @joinable;

		&reportAndLogStatus("$thread_count threads exists. $running_count running and $joinable_count joinable", 10, "\n");#->952

		foreach my $threadID (keys %threadHsh) {
			if (not $threadHsh{$threadID}->is_running() or $threadHsh{$threadID}->is_joinable() or $threadHsh{$threadID}->is_detached()) {
				&reportAndLogStatus("thread $threadID is finishing.", 10, "\n");#->952
				$threadHsh{$threadID}->join();
				delete $threadHsh{$threadID};
			}
		}
		sleep 10;
	}

	return ();
}
sub readLibInfo {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 3_generate_chunk|144
#	secondaryAppearInSection: >none
#	input: $lib_list_path
#	output: $lib_info_hsh_ref
#	toCall: my ($lib_info_hsh_ref) = &readLibInfo($lib_list_path);
#	calledInLine: 151
#....................................................................................................................................................#
	my ($lib_list_path) = @_;
	
	my $lib_info_hsh_ref = {};
	open LIBINFO, "<", $lib_list_path;
	while (<LIBINFO>) {
		chomp;
		my ($libID, $collapse_ctss, $unencoded_G_collapse_ctss) = split /\t/;
		$lib_info_hsh_ref->{$libID}{'collapse_ctss'} = $collapse_ctss;
		$lib_info_hsh_ref->{$libID}{'unencoded_G_collapse_ctss'} = $unencoded_G_collapse_ctss;
	}

	return ($lib_info_hsh_ref);
}
sub readParameters {
#....................................................................................................................................................#
#	subroutineCategory: general
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 0_startingTasks|105
#	secondaryAppearInSection: >none
#	input: none
#	output: $genome, $lib_list_path, $max_thread, $outDir, $outputPrefix, $overwrite
#	toCall: my ($lib_list_path, $max_thread, $genome, $outputPrefix, $outDir, $overwrite) = &readParameters();
#	calledInLine: 108
#....................................................................................................................................................#
	
	my ($lib_list_path, $max_thread, $genome, $outputPrefix, $outDir, $overwrite);
	
	$overwrite = 'no';
	$max_thread = 5;

	GetOptions 	(
		"lib_list_path=s"	=>	\$lib_list_path,
		"max_thread:i"		=>	\$max_thread,
		"genome=s"			=>	\$genome,
		"outputPrefix=s"	=>	\$outputPrefix,
		"outDir:s"			=>	\$outDir,
		"overwrite:s"		=>	\$overwrite,
		'help'				=>	sub { HelpMessage(0) },
	) or HelpMessage(1);

	HelpMessage(1) unless $lib_list_path;
	
	#---check file
	my $file_check_hsh_ref = {
		'lib_list_path' => $lib_list_path,
	};
	
	foreach my $option_name (keys %{$file_check_hsh_ref}) {
		my $file_path = $file_check_hsh_ref->{$option_name};
		die "Quitting: File $option_name does not exists at $file_path" if not -s $file_path;
	}
	
	chop $outDir if ($outDir =~ m/\/$/); #---remove the last slash
	system "mkdir -p -m 755 $outDir/";

	return($lib_list_path, $max_thread, $genome, $outputPrefix, $outDir, $overwrite);

}
sub reportAndLogStatus {
#....................................................................................................................................................#
#	subroutineCategory: log
#	dependOnSub: currentTime|420
#	appearInSub: checkAllExecutable|203, checkChunkResults|323, checkTabixBgzipCtss|346, generateChunkInfoHsh|464, poolChunkResults|561, poolLibCTSSPerChunk|608, processPerChunk|801
#	primaryAppearInSection: >none
#	secondaryAppearInSection: 2_defineOutDirPath|125, 3_generate_chunk|144, 4_convert|157
#	input: $lineEnd, $message, $numTrailingSpace
#	output: 
#	toCall: &reportAndLogStatus($message, $numTrailingSpace, $lineEnd);
#	calledInLine: 226, 231, 240, 249, 258, 267, 276, 285, 294, 339, 380, 384, 388, 487, 588, 593, 596, 601, 629, 640, 835, 842, 845, 849, 866, 870
#....................................................................................................................................................#
	my ($message, $numTrailingSpace, $lineEnd) = @_;

	my $trailingSpaces = '';
	$trailingSpaces .= " " for (1..$numTrailingSpace);
	
	print "[".&currentTime()."] ".$message.$trailingSpaces.$lineEnd;#->420
	print $tmplog_fh "[".&currentTime()."] ".$message.$lineEnd if $lineEnd ne "\r";#->420
	
	return ();
}
sub timeStamp {
#....................................................................................................................................................#
#	subroutineCategory: time, general
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: >none
#	secondaryAppearInSection: >none
#	input: none
#	output: $curntTimeStamp
#	toCall: my ($curntTimeStamp) = &timeStamp();
#	calledInLine: 93
#....................................................................................................................................................#
	
	my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime(time);
	my $curntTimeStamp = sprintf "%04d.%02d.%02d.%02d.%02d.%02d", $year+1900,$mon+1,$mday,$hour,$min,$sec;	

	return ($curntTimeStamp);
}

exit;


















































