#!/usr/bin/perl -w

# This chunk of stuff was generated by App::FatPacker. To find the original
# file's code, look for the end of this BEGIN block or the string 'FATPACK'
BEGIN {
my %fatpacked;

s/^  //mg for values %fatpacked;

my $class = 'FatPacked::'.(0+\%fatpacked);
no strict 'refs';
*{"${class}::files"} = sub { keys %{$_[0]} };

if ($] < 5.008) {
  *{"${class}::INC"} = sub {
    if (my $fat = $_[0]{$_[1]}) {
      my $pos = 0;
      my $last = length $fat;
      return (sub {
        return 0 if $pos == $last;
        my $next = (1 + index $fat, "\n", $pos) || $last;
        $_ .= substr $fat, $pos, $next - $pos;
        $pos = $next;
        return 1;
      });
    }
  };
}

else {
  *{"${class}::INC"} = sub {
    if (my $fat = $_[0]{$_[1]}) {
      open my $fh, '<', \$fat
        or die "FatPacker error loading $_[1] (could be a perl installation issue?)";
      return $fh;
    }
    return;
  };
}

unshift @INC, bless \%fatpacked, $class;
  } # END OF FATPACK CODE


#====================================================================================================================================================#
#<use>
$|++; #---turn on the auto flush for the progress bar
use warnings;
use strict;
use Getopt::Long 'HelpMessage';
use Time::HiRes qw( time );
use File::Spec::Functions qw(rel2abs abs2rel);
use Cwd 'abs_path';
#<\use>
#====================================================================================================================================================#

#====================================================================================================================================================#
#<doc>
=head1 SYNOPSIS

                      O~~~AA      O~~         O~       O~~~~~~~AO~~~~~~~~A
                    O~~    O~~ O~~   O~~     O~ ~~     O~~      O~~       
                     O~~      O~~           O~  O~~    O~~      O~~       
                       O~~    O~~          O~~   O~~   O~~~~~AA O~~~~~~A  
                          O~~ O~~         O~~~~~A O~~  O~~      O~~       
                    O~~    O~~ O~~   O~~ O~~       O~~ O~~      O~~       
                      O~~~~A     O~~~   O~~         O~~O~~      O~~~~~~~AA

 Single Cell Analysis of Five'End (SCAFE) Suite: --> workflow.bk.pool.pl <--

   This workflow process a single sample, from a bulk CAGE bam file to read count per tCRE per sample

   workflow.sc.pool.pl [options] --lib_list_path --genome --run_tag --run_outDir

 Required:
   --lib_list_path         [required] [string] a list of libraries, in formation of 
                                               <lib_ID><\t><long_ctss_bed><\t><collapse_ctss_bed>
                                               lib_ID = Unique ID of the cellbarcode
                                               long_ctss_bed = *long.ctss.bed.gz from tool.bk.bam_to_ctss.pl, 
                                               collapse_ctss_bed = *collapse.ctss.bed.gz from tool.bk.bam_to_ctss.pl, 
   --genome                [required] [string] name of genome reference, e.g. hg19.gencode_v32lift37
   --run_tag               [required] [string] prefix for the output files
   --run_outDir            [required] [string] directory for the output files

 Optional:
   --training_signal_path  [optional] [string] quantitative signal (e.g. ATAC -logP, in bigwig format), or binary genomic 
                                               regions (e.g. annotated CRE, in bed format) used for training of logical 
                                               regression model If null, $usr_glm_model_path must be supplied for 
                                               pre-built logical regression model. It overrides usr_glm_model_path 
                                               (default=null)
   --testing_signal_path  [optional] [string]  quantitative signal (e.g. ATAC -logP, in bigwig format), or binary genomic 
                                               regions (e.g. annotated CRE, in bed format) used for testing the performance 
                                               of the logical regression model. If null, annotated TSS from $genome will be 
                                               used as binary genomic regions. (default=null)
   --max_thread           [optional] [integer] maximum number of parallel threads, capped at 10 to 
                                               avoid memory overflow (default=5)
   --overwrite            [optional] [yes/no]  erase run_outDir before running (default=no)

 Dependencies:
   R packages: 'ROCR','PRROC', 'caret', 'e1071', 'ggplot2', 'scales', 'reshape2'
   bigWigAverageOverBed
   bedGraphToBigWig
   bedtools
   samtools
   paraclu
   paraclu-cut.sh
   
 For demo without training, cd to SCAFE dir and run,
   ./scripts/workflow.bk.pool.pl \
   --overwrite=yes \
   --lib_list_path=./demo/input/bk.pool/lib_list_path.txt \
   --genome=hg19.gencode_v32lift37 \
   --run_tag=demo \
   --run_outDir=./demo/output/bk.pool/

 For demo with training, cd to SCAFE dir and run,
   ./scripts/workflow.bk.pool.pl \
   --overwrite=yes \
   --lib_list_path=./demo/input/bk.pool/lib_list_path.txt \
   --genome=hg19.gencode_v32lift37 \
   --training_signal_path=./demo/input/atac/demo.atac.bw \
   --testing_signal_path=./demo/input/atac/demo.atac.bw \
   --run_tag=demo \
   --run_outDir=./demo/output/bk.pool/

=head1 VERSION

1.0

=cut
#<\doc>
#====================================================================================================================================================#

#====================================================================================================================================================#
#<lastCmdCalled>
#
#	notCalledBefore
#
#	notCalledBefore
#
#<\lastCmdCalled>
#====================================================================================================================================================#

#====================================================================================================================================================#
#<global>
#<\global>
#====================================================================================================================================================#

#====================================================================================================================================================#
{	#Main sections lexical scope starts
#====================================================================================================================================================#

#====================================================================================================================================================#
#	section 0_startTasks
#
#<section ID="startTasks" num="0">
my $ARGV_ary_ref = [@ARGV];
my ($lib_list_path, $genome, $training_signal_path, $testing_signal_path, $max_thread, $run_tag, $run_outDir, $overwrite) = &readParameters();#->409
my ($scafe_dir, $script_dir, $result_script_dir, $ARGVStr, $scriptAbsPath) = &prepDir($run_outDir, $ARGV_ary_ref);#->381
&logCalledCMDAndScript($ARGVStr, $result_script_dir, $scriptAbsPath);#->356
#<\section>
#====================================================================================================================================================#

#====================================================================================================================================================#
#	section 1_run
#
#<section ID="run" num="1">
my ($path_hsh_ref) = &define_path($run_outDir, $run_tag, $lib_list_path, $training_signal_path, $testing_signal_path, $script_dir);#->208
my ($task_info_hsh_ref) = &define_task($genome, $path_hsh_ref, $max_thread, $run_tag, $run_outDir);#->254
&addCountIndivLibTask($path_hsh_ref, $task_info_hsh_ref, $run_tag, $run_outDir);#->150
&run_task($task_info_hsh_ref, $path_hsh_ref);#->459
#<\section>
#====================================================================================================================================================#

#====================================================================================================================================================#
}	#Main sections lexical scope ends
#====================================================================================================================================================#

#====================================================================================================================================================#
#List of subroutines by category
#
#	general [n=3]:
#		currentTime, logCalledCMDAndScript, readParameters
#
#	unassigned [n=5]:
#		addCountIndivLibTask, define_path, define_task
#		prepDir, run_task
#
#====================================================================================================================================================#

sub addCountIndivLibTask {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 1_run|123
#	secondaryAppearInSection: >none
#	input: $path_hsh_ref, $run_outDir, $run_tag, $task_info_hsh_ref
#	output: 
#	toCall: &addCountIndivLibTask($path_hsh_ref, $task_info_hsh_ref, $run_tag, $run_outDir);
#	calledInLine: 128
#....................................................................................................................................................#
	my ($path_hsh_ref, $task_info_hsh_ref, $run_tag, $run_outDir) = @_;
	
	my $task_num = keys %{$task_info_hsh_ref};
	open CTSSLIST, "<", $path_hsh_ref->{'lib_list_path'};
	while (<CTSSLIST>) {
		chomp;
			my ($libID, $long_ctss_bed_path, $collapse_ctss_bed_path) = split /\t/;
		my $outputPrefix = $libID;
		my $task_outDir = "$run_outDir/count/";
		$task_num++;
		$task_info_hsh_ref->{$task_num} = {
			'task_name' => 'count',
			'script_name' => 'tool.bk.count.pl',
			'param' => [
				['countRegion_bed_path', $path_hsh_ref->{"tCRE_bed_path"}],
				['ctss_bed_path', $collapse_ctss_bed_path],
				['outputPrefix', $outputPrefix],
				['outDir', $run_outDir."/count"],
			],
			'check' => [
				$run_outDir."/count/$outputPrefix/log/count.log.tsv",
			]
		};
	}
	close CTSSLIST;

	return ();
}
sub currentTime {
#....................................................................................................................................................#
#	subroutineCategory: general
#	dependOnSub: >none
#	appearInSub: prepDir|381
#	primaryAppearInSection: >none
#	secondaryAppearInSection: 0_startTasks|112
#	input: none
#	output: $runTime
#	toCall: my ($runTime) = &currentTime();
#	calledInLine: 395
#....................................................................................................................................................#
	
	my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime(time);
	my $runTime = sprintf "%04d-%02d-%02d %02d:%02d", $year+1900, $mon+1,$mday,$hour,$min;	
	
	return $runTime;
}
sub define_path {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 1_run|123
#	secondaryAppearInSection: >none
#	input: $lib_list_path, $run_outDir, $run_tag, $script_dir, $testing_signal_path, $training_signal_path
#	output: $path_hsh_ref
#	toCall: my ($path_hsh_ref) = &define_path($run_outDir, $run_tag, $lib_list_path, $training_signal_path, $testing_signal_path, $script_dir);
#	calledInLine: 126
#....................................................................................................................................................#

	my ($run_outDir, $run_tag, $lib_list_path, $training_signal_path, $testing_signal_path, $script_dir) = @_;
	
	my $path_hsh_ref = {
		'script_dir' => $script_dir,

		'lib_list_path' => $lib_list_path,
		'training_signal_path' => $training_signal_path,
		'testing_signal_path' => $testing_signal_path,

		'long_ctss_bed_path' => $run_outDir."/pool/".$run_tag."/bed/".$run_tag.".pool.long.ctss.bed.gz",
		'ung_ctss_bed_path' => $run_outDir."/pool/".$run_tag."/bed/".$run_tag.".pool.unencoded_G.collapse.ctss.bed.gz",
		'collapse_ctss_bed_path' => $run_outDir."/pool/".$run_tag."/bed/".$run_tag.".pool.collapse.ctss.bed.gz",
		'raw_tssCluster_bed_path' => $run_outDir."/cluster/".$run_tag."/bed/".$run_tag.".tssCluster.bed.gz",
		'filtered_tssCluster_info_path' => $run_outDir."/filter/".$run_tag."/log/".$run_tag.".tssCluster.log.tsv",

		'bw_cpm_rev_path' => $run_outDir."/ctss_to_bigwig/".$run_tag."/wig/".$run_tag.".cpm.rev.bw",
		'bw_cpm_fwd_path' => $run_outDir."/ctss_to_bigwig/".$run_tag."/wig/".$run_tag.".cpm.fwd.bw",
		'bw_count_rev_path' => $run_outDir."/ctss_to_bigwig/".$run_tag."/wig/".$run_tag.".count.rev.bw",
		'bw_count_fwd_path' => $run_outDir."/ctss_to_bigwig/".$run_tag."/wig/".$run_tag.".count.fwd.bw",

		'tCRE_bed_path' => $run_outDir."/annotate/".$run_tag."/bed/".$run_tag.".CRE.coord.bed.gz",
		'tCRE_info_path' => $run_outDir."/annotate/".$run_tag."/log/".$run_tag.".CRE.info.tsv.gz",
		'tssCluster_bed_path' => $run_outDir."/annotate/".$run_tag."/bed/".$run_tag.".cluster.coord.bed.gz",
		'tssCluster_info_path' => $run_outDir."/annotate/".$run_tag."/log/".$run_tag.".cluster.info.tsv.gz",
	};

	foreach my $level (qw/robust lenient default/) {
		$path_hsh_ref->{"$level.filtered_tssCluster_bed_path"} = $run_outDir."/filter/".$run_tag."/bed/".$run_tag.".tssCluster.".$level.".filtered.bed.gz";
	}

	return ($path_hsh_ref);

}
sub define_task {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 1_run|123
#	secondaryAppearInSection: >none
#	input: $genome, $max_thread, $path_hsh_ref, $run_outDir, $run_tag
#	output: $task_info_hsh_ref
#	toCall: my ($task_info_hsh_ref) = &define_task($genome, $path_hsh_ref, $max_thread, $run_tag, $run_outDir);
#	calledInLine: 127
#....................................................................................................................................................#

	my ($genome, $path_hsh_ref, $max_thread, $run_tag, $run_outDir) = @_;

	my $task_info_hsh_ref = {
		1 => {
			'task_name' => 'pool',
			'script_name' => 'tool.bk.pool.pl',
			'param' => [
				['lib_list_path', $path_hsh_ref->{'lib_list_path'}],
				['max_thread', $max_thread],
				['genome', $genome],
				['outputPrefix', $run_tag],
				['outDir', $run_outDir."/pool"],
			],
			'check' => [
				 $path_hsh_ref->{'ung_ctss_bed_path'},
				 $path_hsh_ref->{'collapse_ctss_bed_path'},
				 $path_hsh_ref->{'long_ctss_bed_path'},
			]
		},
		2 => {
			'task_name' => 'cluster',
			'script_name' => 'tool.cm.cluster.pl',
			'param' => [
				['cluster_ctss_bed_path', $path_hsh_ref->{'collapse_ctss_bed_path'}],
				['count_ctss_bed_path_list', $path_hsh_ref->{'collapse_ctss_bed_path'}],
				['count_scope_bed_path', $path_hsh_ref->{'collapse_ctss_bed_path'}],
				['outputPrefix', $run_tag],
				['outDir', $run_outDir."/cluster"],
			],
			'check' => [
				 $path_hsh_ref->{'raw_tssCluster_bed_path'},
			]
		},
		3 => {
			'task_name' => 'filter',
			'script_name' => 'tool.cm.filter.pl',
			'param' => [
				['genome', $genome],
				['training_signal_path', $path_hsh_ref->{'training_signal_path'}],
				['testing_signal_path', $path_hsh_ref->{'testing_signal_path'}],
				['ung_ctss_bed_path', $path_hsh_ref->{'ung_ctss_bed_path'}],
				['tssCluster_bed_path', $path_hsh_ref->{'raw_tssCluster_bed_path'}],
				['ctss_bed_path', $path_hsh_ref->{'collapse_ctss_bed_path'}],
				['outputPrefix', $run_tag],
				['outDir', $run_outDir."/filter"],
			],
			'check' => [
				 $path_hsh_ref->{'default.filtered_tssCluster_bed_path'},
				 $path_hsh_ref->{'robust.filtered_tssCluster_bed_path'},
				 $path_hsh_ref->{'lenient.filtered_tssCluster_bed_path'},
			]
		},
		4 => {
			'task_name' => 'ctss_to_bigwig',
			'script_name' => 'tool.cm.ctss_to_bigwig.pl',
			'param' => [
				['genome', $genome],
				['ctss_bed_path', $path_hsh_ref->{'collapse_ctss_bed_path'}],
				['outputPrefix', $run_tag],
				['outDir', $run_outDir."/ctss_to_bigwig"],
			],
			'check' => [
				 $path_hsh_ref->{'bw_cpm_rev_path'},
				 $path_hsh_ref->{'bw_cpm_fwd_path'},
				 $path_hsh_ref->{'bw_count_rev_path'},
				 $path_hsh_ref->{'bw_count_fwd_path'},
			]
		},
		5 => {
			'task_name' => 'annotate',
			'script_name' => 'tool.cm.annotate.pl',
			'param' => [
				['genome', $genome],
				['tssCluster_bed_path', $path_hsh_ref->{"default.filtered_tssCluster_bed_path"}],
				['tssCluster_info_path', $path_hsh_ref->{'filtered_tssCluster_info_path'}],
				['outputPrefix', $run_tag],
				['outDir', $run_outDir."/annotate"],
			],
			'check' => [
				$path_hsh_ref->{"tCRE_bed_path"},
				$path_hsh_ref->{"tCRE_info_path"},
				$path_hsh_ref->{"tssCluster_bed_path"},
				$path_hsh_ref->{"tssCluster_info_path"},
			]
		},
	};
	
	return($task_info_hsh_ref);
}
sub logCalledCMDAndScript {
#....................................................................................................................................................#
#	subroutineCategory: general
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 0_startTasks|112
#	secondaryAppearInSection: >none
#	input: $ARGVStr, $result_script_dir, $scriptAbsPath
#	output: 
#	toCall: &logCalledCMDAndScript($ARGVStr, $result_script_dir, $scriptAbsPath);
#	calledInLine: 118
#....................................................................................................................................................#
	my ($ARGVStr, $result_script_dir, $scriptAbsPath) = @_;


	my $cpScriptPath = "$result_script_dir/script.ran.pl";
	my $calledCMDPath = "$result_script_dir/called.cmd.txt";
	system "cp -f $scriptAbsPath $cpScriptPath";
	system "chmod 0444 $cpScriptPath"; #---[07/03/2014 18:02] make it read-only to make sure there'll be accodental change of parameters
	open CALLEDCMD, ">", $calledCMDPath;
	print CALLEDCMD join "", ($ARGVStr), "\n";
	close CALLEDCMD;
	
	return ();
}
sub prepDir {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: currentTime|190
#	appearInSub: >none
#	primaryAppearInSection: 0_startTasks|112
#	secondaryAppearInSection: >none
#	input: $ARGV_ary_ref, $run_outDir
#	output: $ARGVStr, $result_script_dir, $scafe_dir, $scriptAbsPath, $script_dir
#	toCall: my ($scafe_dir, $script_dir, $result_script_dir, $ARGVStr, $scriptAbsPath) = &prepDir($run_outDir, $ARGV_ary_ref);
#	calledInLine: 117
#....................................................................................................................................................#
	my ($run_outDir, $ARGV_ary_ref) = @_;

	my $scriptAbsPath = abs_path($0);
	my $ARGVStr = join "\n", (&currentTime(), $scriptAbsPath, @{$ARGV_ary_ref});#->190
	my @path_split = split /\//, $scriptAbsPath;
	my $scafe_dir_index = $#path_split-2;
	my $script_dir_index = $#path_split-1;
	my $scafe_dir = join "/", @path_split[0..$scafe_dir_index];
	my $script_dir = join "/", @path_split[0..$script_dir_index];

	my @mkDirAry;
	my $result_script_dir = "$run_outDir/script/"; push @mkDirAry, $result_script_dir;
	foreach my $dir (@mkDirAry) {system ("mkdir -pm 755 $dir");}

	return ($scafe_dir, $script_dir, $result_script_dir, $ARGVStr, $scriptAbsPath);
}
sub readParameters {
#....................................................................................................................................................#
#	subroutineCategory: general
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 0_startTasks|112
#	secondaryAppearInSection: >none
#	input: none
#	output: $genome, $lib_list_path, $max_thread, $overwrite, $run_outDir, $run_tag, $testing_signal_path, $training_signal_path
#	toCall: my ($lib_list_path, $genome, $training_signal_path, $testing_signal_path, $max_thread, $run_tag, $run_outDir, $overwrite) = &readParameters();
#	calledInLine: 116
#....................................................................................................................................................#
	
	my ($lib_list_path, $genome, $training_signal_path, $testing_signal_path, $max_thread, $run_tag, $run_outDir, $overwrite);

	$overwrite = 'no';
	$max_thread = 5;
	
	GetOptions 	(
		"lib_list_path=s"				=>	\$lib_list_path,
		"genome=s"						=>	\$genome,
		"max_thread:i"					=>	\$max_thread,
		"training_signal_path:s"	=>	\$training_signal_path,
		"testing_signal_path:s"		=>	\$testing_signal_path,
		"run_tag=s"						=>	\$run_tag,
		"run_outDir=s"					=>	\$run_outDir,
		"overwrite:s"					=>	\$overwrite,
		'help'							=>	sub { HelpMessage(0) },
	) or HelpMessage(1);

	HelpMessage(1) unless $lib_list_path;

	#---check file
	my $file_check_hsh_ref = {
		'lib_list_path' => $lib_list_path,
	};
	
	foreach my $option_name (keys %{$file_check_hsh_ref}) {
		my $file_path = $file_check_hsh_ref->{$option_name};
		die "Quitting: File $option_name does not exists at $file_path" if not -s $file_path;
	}

	system "rm -rf $run_outDir" if ($overwrite eq 'yes');

	chop $run_outDir if ($run_outDir =~ m/\/$/); #---remove the last slash
	system "mkdir -p -m 755 $run_outDir/";
	
	return($lib_list_path, $genome, $training_signal_path, $testing_signal_path, $max_thread, $run_tag, $run_outDir, $overwrite);

}
sub run_task {
#....................................................................................................................................................#
#	subroutineCategory: unassigned
#	dependOnSub: >none
#	appearInSub: >none
#	primaryAppearInSection: 1_run|123
#	secondaryAppearInSection: >none
#	input: $path_hsh_ref, $task_info_hsh_ref
#	output: none
#	toCall: &run_task($task_info_hsh_ref, $path_hsh_ref);
#	calledInLine: 129
#....................................................................................................................................................#
	
	my ($task_info_hsh_ref, $path_hsh_ref) = @_;
	
	foreach my $task_num (sort {$a <=> $b} keys %{$task_info_hsh_ref}) {
		my $task_name = $task_info_hsh_ref->{$task_num}{'task_name'};
		my $script_name = $task_info_hsh_ref->{$task_num}{'script_name'};
		my $result_found = 'yes';
		foreach my $check_path (@{$task_info_hsh_ref->{$task_num}{'check'}}) {
			$result_found = 'no' if not -s $check_path;
		}
		
		if ($result_found eq 'no') {

			print "#===========================#\n";
			print "Start running $task_name\n";
			print "#===========================#\n";

			my $script_path = $path_hsh_ref->{'script_dir'}.'/'.$script_name;
			die "script of $task_name does not exist at $script_path\n" if not -s $script_path;
			my @cmd_param_ary = ($script_path);
			foreach my $indiv_param_ary_ref (@{$task_info_hsh_ref->{$task_num}{'param'}}) {
				my ($param_name, $param_val) = @{$indiv_param_ary_ref};
				if (defined $param_val) {#---[2020/10/07 20:32] specifically for skipping training_signal_path if not input
					push @cmd_param_ary, "--$param_name=$param_val";
				}
			}
			my $cmd = join " ", @cmd_param_ary;
			system "$cmd";

		} else {
			print "#=====================================#\n";
			print "Results of $task_name found. Skipping.\n";
			print "#=====================================#\n";
		}
	}
}

exit;


















































